extends Node3D

var eva: EVAController
var ship: ShipController
var scanner: ScannerSystem
var archaeology: ArchaeologySystem
var tutorial: TutorialDirector
var mobile_controls: MobileControls
var campaign: CampaignState
var campaign_world: CampaignWorld
var sample: Interactable
var ruin: Interactable
var hud_title: Label
var hud_detail: Label
var hud_progress: ProgressBar
var hint_label: Label
var scan_label: Label
var scan_bar: ProgressBar
var campaign_label: Label
var ship_status_label: Label
var mode := "eva"
var sample_collected := false
var intro_camera: Camera3D
var environment: Environment
var cutscene_active := false
var boarding_range := 5.0
var world_art := {}
var active_campaign_fragment := ""
var current_world := "Tethys"
var _intro_tween: Tween

func _ready() -> void:
	InputBootstrap.ensure_actions()
	campaign = CampaignState.new()
	var saved := SaveSystem.load_state()
	if saved.has("campaign") and saved["campaign"] is Dictionary:
		campaign.restore(saved["campaign"] as Dictionary)
	_build_environment()
	_build_world()
	_build_ui()
	_connect_systems()
	campaign_world.restore_collected_sites()
	ship.apply_campaign_upgrades(campaign.upgrades)
	campaign.select_objective_world()
	_set_nav_destination(campaign.selected_world)
	_set_mode("eva")
	tutorial.start()
	_restore_first_hour_progress()
	_update_campaign_ui()

func _process(delta: float) -> void:
	if Input.is_action_just_pressed("cutscene_skip") and cutscene_active:
		_finish_cutscene()
	var actor_position := eva.global_position if mode == "eva" else ship.global_position
	current_world = campaign_world.update_context(actor_position, environment)
	if mode == "eva" and not cutscene_active:
		scanner.tick(delta, eva.camera, true)
		archaeology.tick(delta)
		_update_interaction_hint()
	else:
		scanner.tick(delta, eva.camera, false)
	if Input.is_action_just_pressed("tutorial"):
		hud_title.visible = not hud_title.visible
		hud_detail.visible = hud_title.visible
		hud_progress.visible = hud_title.visible
	if not cutscene_active and Input.is_action_just_pressed("route_next") and mode == "ship":
		_cycle_route()
	if Input.is_action_just_pressed("interact") and not cutscene_active:
		if mode == "eva": _handle_interaction()
		elif ship.landed: _disembark()
	_update_campaign_ui()

func _build_environment() -> void:
	var env_node := WorldEnvironment.new()
	environment = Environment.new()
	environment.background_mode = Environment.BG_COLOR
	environment.background_color = Color("#6f8894")
	environment.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	environment.ambient_light_color = Color("#9fb8bb")
	environment.ambient_light_energy = 0.75
	environment.fog_enabled = true
	environment.fog_light_color = Color("#70888d")
	environment.fog_density = 0.0025
	env_node.environment = environment
	add_child(env_node)
	var sun := DirectionalLight3D.new()
	sun.rotation_degrees = Vector3(-52, -34, 0)
	sun.light_energy = 1.25
	sun.shadow_enabled = true
	add_child(sun)

func _build_world() -> void:
	campaign_world = CampaignWorld.new()
	campaign_world.name = "CampaignWorld"
	add_child(campaign_world)
	campaign_world.setup(campaign)

	# Dense opening reeds remain local to Tethys. The rest of the system uses
	# authored per-world landmarks/sites generated by CampaignWorld.
	for i in range(26):
		var reed := MeshInstance3D.new()
		var reed_mesh := CylinderMesh.new()
		reed_mesh.top_radius = 0.04
		reed_mesh.bottom_radius = 0.07
		reed_mesh.height = 1.1 + float(i % 5) * 0.16
		reed.mesh = reed_mesh
		reed.position = Vector3(-18 + (i * 7) % 42, reed_mesh.height * 0.5, -16 - (i * 11) % 40)
		add_child(reed)

	eva = EVAController.new()
	eva.name = "EVA"
	eva.position = Vector3(0, 1.0, 5.5)
	add_child(eva)

	ship = ShipController.new()
	ship.name = "Ship"
	ship.position = Vector3(0, 1.0, 0)
	ship.surface_query = Callable(campaign_world, "surface_info")
	add_child(ship)
	var ship_fallback := MeshInstance3D.new()
	var ship_mesh := BoxMesh.new()
	ship_mesh.size = Vector3(2.0, 1.0, 4.0)
	var ship_mat := StandardMaterial3D.new()
	ship_mat.albedo_color = Color("#2a3945")
	ship_mat.metallic = 0.55
	ship_mat.roughness = 0.38
	ship_mesh.material = ship_mat
	ship_fallback.mesh = ship_mesh
	ship.add_child(AssetLoader.instantiate_or_fallback("ship", ship_fallback))

	sample = _make_interactable("field_sample", "Pale Reed Sample", Vector3(6, 0.8, -7), true)
	ruin = _make_interactable("foundation", "Buried Foundation Seam", Vector3(-8, 0.8, -14), false)
	var ruin_mesh := ruin.get_node("Visual") as MeshInstance3D
	if ruin_mesh:
		var b := BoxMesh.new()
		b.size = Vector3(4.2, 0.55, 2.1)
		ruin_mesh.mesh = b
	WorldArt.decorate_training_foundation(ruin)

	scanner = ScannerSystem.new()
	add_child(scanner)
	archaeology = ArchaeologySystem.new()
	add_child(archaeology)
	tutorial = TutorialDirector.new()
	add_child(tutorial)

	intro_camera = Camera3D.new()
	intro_camera.position = Vector3(14, 9, 18)
	intro_camera.look_at_from_position(intro_camera.position, Vector3(0, 1, -5), Vector3.UP)
	add_child(intro_camera)

	# Art replacement remains isolated from mechanic/collision anchors.
	world_art = WorldArt.install(self, eva)

func _make_interactable(id: String, label: String, position_: Vector3, scan_required: bool) -> Interactable:
	var area := Interactable.new()
	area.interaction_id = id
	area.display_name = label
	area.requires_scan = scan_required
	area.position = position_
	var visual := MeshInstance3D.new()
	visual.name = "Visual"
	var sphere := SphereMesh.new()
	sphere.radius = 0.55
	sphere.height = 1.1
	visual.mesh = sphere
	area.add_child(visual)
	var collision := CollisionShape3D.new()
	var cshape := SphereShape3D.new()
	cshape.radius = 0.75
	collision.shape = cshape
	area.add_child(collision)
	add_child(area)
	return area

func _build_ui() -> void:
	var layer := CanvasLayer.new()
	add_child(layer)
	var panel := PanelContainer.new()
	panel.position = Vector2(18, 18)
	panel.size = Vector2(470, 150)
	layer.add_child(panel)
	var box := VBoxContainer.new()
	panel.add_child(box)
	hud_title = Label.new()
	hud_title.add_theme_font_size_override("font_size", 18)
	box.add_child(hud_title)
	hud_detail = Label.new()
	hud_detail.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	box.add_child(hud_detail)
	hud_progress = ProgressBar.new()
	hud_progress.max_value = 1.0
	box.add_child(hud_progress)

	campaign_label = Label.new()
	campaign_label.position = Vector2(820, 18)
	campaign_label.size = Vector2(440, 90)
	campaign_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT
	campaign_label.add_theme_font_size_override("font_size", 16)
	layer.add_child(campaign_label)
	ship_status_label = Label.new()
	ship_status_label.position = Vector2(820, 108)
	ship_status_label.size = Vector2(440, 50)
	ship_status_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT
	layer.add_child(ship_status_label)

	hint_label = Label.new()
	hint_label.position = Vector2(18, 680)
	layer.add_child(hint_label)
	scan_label = Label.new()
	scan_label.position = Vector2(510, 610)
	layer.add_child(scan_label)
	scan_bar = ProgressBar.new()
	scan_bar.position = Vector2(510, 636)
	scan_bar.size = Vector2(260, 18)
	scan_bar.max_value = 1.0
	layer.add_child(scan_bar)
	var footer := Label.new()
	footer.position = Vector2(18, 650)
	footer.text = "WASD MOVE/THROTTLE · MOUSE LOOK ≠ STEERING · F/RMB SCAN · E BOARD/EXIT/USE · N NAV · TAB ROUTE · X BRAKE"
	footer.visible = not DisplayServer.is_touchscreen_available()
	layer.add_child(footer)
	mobile_controls = MobileControls.new()
	layer.add_child(mobile_controls)

func _connect_systems() -> void:
	eva.moved.connect(func(d): tutorial.event("eva_moved", d))
	eva.looked.connect(func(d): tutorial.event("eva_looked", d))
	scanner.atmosphere_verified.connect(func(): tutorial.event("atmosphere_verified"))
	scanner.subject_scanned.connect(_on_subject_scanned)
	scanner.scan_progress.connect(func(value, label): scan_bar.value = value; scan_label.text = label)
	archaeology.reconstruction_progress.connect(func(value): scan_bar.value = value)
	archaeology.reconstruction_state.connect(_on_reconstruction_state)
	archaeology.reconstruction_complete.connect(_on_reconstruction_complete)
	ship.launched.connect(func(): tutorial.event("launched"))
	ship.crossed_atmosphere.connect(func(): tutorial.event("crossed_atmosphere"))
	ship.nav_state_changed.connect(func(state): tutorial.event("nav_state", state); hint_label.text = "NAV %s · %s" % [state, campaign.selected_world])
	ship.touchdown.connect(_on_touchdown)
	ship.fuel_changed.connect(func(_value, _maximum): _update_campaign_ui())
	ship.hull_changed.connect(func(_value, _maximum): _update_campaign_ui())
	campaign_world.world_changed.connect(_on_world_changed)
	tutorial.objective_changed.connect(func(title, detail, progress): hud_title.text = title; hud_detail.text = detail; hud_progress.value = progress)
	tutorial.lesson_completed.connect(func(_id): _save_game())
	tutorial.tutorial_completed.connect(_on_tutorial_completed)
	tutorial.request_intro_cutscene.connect(_play_intro_cutscene)
	tutorial.request_reveal_cutscene.connect(_play_reveal_cutscene)
	mobile_controls.look_delta.connect(_on_mobile_look)

func _is_touch_input() -> bool:
	return DisplayServer.is_touchscreen_available()

func _on_reconstruction_state(stage: String, alignment: float, target: float, lock_ready: bool) -> void:
	if not archaeology.active and stage != "RECONSTRUCTION LOCKED":
		return
	var delta := target - alignment
	var direction: String
	if _is_touch_input():
		direction = "HOLD · USE LOCK" if lock_ready else ("LEFT STICK · SHIFT LEFT" if delta < 0.0 else "LEFT STICK · SHIFT RIGHT")
	else:
		direction = "HOLD · E LOCK" if lock_ready else ("A · SHIFT LEFT" if delta < 0.0 else "D · SHIFT RIGHT")
	scan_label.text = "%s · %s · OFFSET %.2f" % [stage, direction, absf(delta)]

func _restore_first_hour_progress() -> void:
	# Tutorial completion is the authoritative persisted source for the one-time
	# training specimen. Deriving physical state from it keeps older saves valid
	# without adding another competing save owner.
	var scan_done := tutorial.completed.has("scan")
	var collect_done := tutorial.completed.has("collect")
	sample.scanned = scan_done or collect_done
	_set_sample_collected(collect_done)

func _set_sample_collected(value: bool) -> void:
	sample_collected = value
	sample.completed = value
	sample.visible = not value
	sample.monitoring = not value
	sample.monitorable = not value
	sample.collision_layer = 0 if value else 1
	sample.collision_mask = 0 if value else 1

func _on_mobile_look(delta_pixels: Vector2) -> void:
	if cutscene_active: return
	if mode == "eva": eva.apply_look(delta_pixels)
	else: ship.apply_camera_look(delta_pixels)

func _on_subject_scanned(target: Interactable) -> void:
	if target == sample:
		tutorial.event("subject_scanned", target)
	elif target == ruin:
		archaeology.mark_scanned()
	elif target.interaction_id.begins_with("wildlife|flat_grazer|"):
		hint_label.text = "FIELD NOTE · FLAT GRAZER · PRESSURE-SENSING FAN · DISTURBANCE RESPONSE OBSERVED"

func _handle_interaction() -> void:
	if archaeology.active:
		# The archaeology system consumes the shared interact action only when alignment is valid.
		return
	if eva.global_position.distance_to(ship.global_position) <= boarding_range:
		_set_mode("ship")
		tutorial.event("boarded")
		hint_label.text = "SHIP BOARDED · NAV BUTTON FOR GUIDANCE" if _is_touch_input() else "SHIP BOARDED · N NAV · TAB ROUTE"
		return
	if eva.global_position.distance_to(sample.global_position) <= 2.2:
		if sample.scanned and not sample_collected:
			_set_sample_collected(true)
			tutorial.event("sample_collected")
			hint_label.text = "PHYSICAL SAMPLE SECURED"
		elif not sample.scanned:
			hint_label.text = "IDENTIFY THE SAMPLE WITH THE SCANNER FIRST"
		return
	if eva.global_position.distance_to(ruin.global_position) <= 3.0 and not tutorial.completed.has("archaeology"):
		if not archaeology.active:
			active_campaign_fragment = ""
			archaeology.begin()
			hint_label.text = "SCAN FOUNDATION, THEN LEFT STICK ALIGN · USE LOCK" if _is_touch_input() else "SCAN FOUNDATION, THEN A/D ALIGN · E LOCK"
		return
	var campaign_site := campaign_world.nearest_site(eva.global_position)
	if campaign_site != null:
		_handle_campaign_site(campaign_site)

func _handle_campaign_site(site: Interactable) -> void:
	var id := site.interaction_id
	if not site.scanned:
		hint_label.text = "SCAN %s BEFORE PHYSICAL INTERACTION" % site.display_name.to_upper()
		return
	var parts := id.split("|")
	if parts.is_empty(): return
	match parts[0]:
		"resource":
			if parts.size() < 4: return
			var resource_name := str(parts[2])
			if campaign.collect_resource(resource_name, id):
				campaign_world.mark_site_collected(id)
				hint_label.text = "%s COLLECTED · STORED IN SHIP INVENTORY" % resource_name.to_upper()
				if resource_name in ["Clathrate Pocket", "Sulphur Bloom", "Blue Ice Column", "Abyssal Crystal"]:
					ship.add_fuel(85.0)
				_save_game()
		"fragment":
			if parts.size() < 2: return
			active_campaign_fragment = str(parts[1])
			archaeology.begin()
			archaeology.mark_scanned()
			hint_label.text = "RECONSTRUCT SIGNAL GEOMETRY · LEFT STICK ALIGN · USE LOCK" if _is_touch_input() else "RECONSTRUCT SIGNAL GEOMETRY · A/D ALIGN · E LOCK"
		"ending":
			if campaign.world_unlocked("Nemesis"):
				_finish_campaign()

func _on_reconstruction_complete() -> void:
	if active_campaign_fragment.is_empty():
		tutorial.event("archaeology_complete")
		return
	var fragment_id := active_campaign_fragment
	active_campaign_fragment = ""
	if campaign.collect_fragment(fragment_id):
		campaign_world.mark_site_collected("fragment|" + fragment_id)
		var count := campaign.fragment_count()
		hint_label.text = "FIRST-HOUR EVIDENCE %d / 2 RECOVERED" % mini(count, 2)
		campaign.select_objective_world()
		_set_nav_destination(campaign.selected_world)
		_save_game()
		_update_campaign_ui()

func _disembark() -> void:
	if not ship.landed:
		hint_label.text = "LAND THE SHIP BEFORE EXITING"
		return
	_set_mode("eva")
	hint_label.text = "EVA DEPLOYED · SCAN, COLLECT, RECONSTRUCT"

func _cycle_route() -> void:
	var world := campaign.select_next_world()
	_set_nav_destination(world)
	hint_label.text = "ROUTE SELECTED · %s · N TO TOGGLE NAV GUIDANCE" % world.to_upper()
	_save_game()

func _set_nav_destination(world: String) -> void:
	campaign.selected_world = world
	ship.nav_target = campaign_world.approach_target(world)
	_update_campaign_ui()

func _on_touchdown(v: float, l: float, safe: bool) -> void:
	tutorial.event("touchdown", {"vertical":v, "lateral":l, "safe":safe})
	var exit_hint := "USE TO EXIT" if _is_touch_input() else "E TO EXIT"
	hint_label.text = "TOUCHDOWN %s · V %.1f · L %.1f · %s" % ["SAFE" if safe else "HARD", v, l, exit_hint]
	_save_game()

func _on_world_changed(world: String) -> void:
	current_world = world
	var exit_hint := "USE TO EXIT" if _is_touch_input() else "E TO EXIT"
	hint_label.text = "%s SURFACE ZONE · LAND MANUALLY, THEN %s" % [world.to_upper(), exit_hint]
	_update_campaign_ui()

func _on_tutorial_completed() -> void:
	hint_label.text = "FIELD TRAINING COMPLETE · TETHYS/KESTRA INVESTIGATION ACTIVE"
	campaign.select_objective_world()
	_set_nav_destination(campaign.selected_world)
	_save_game()

func _finish_campaign() -> void:
	campaign.ending_complete = true
	hud_title.visible = true
	hud_detail.visible = true
	hud_progress.visible = true
	hud_title.text = "THE PALE SIGNAL"
	hud_detail.text = "The Nemesis beacon is not a transmitter. It is a receiver — powered, aligned, and waiting for something beyond the Aster system to answer."
	hud_progress.value = 1.0
	hint_label.text = "CAMPAIGN COMPLETE · THE RECEIVER IS STILL LISTENING"
	_save_game()

func _update_interaction_hint() -> void:
	if archaeology.active: return
	var use_label := "USE" if _is_touch_input() else "E"
	if eva.global_position.distance_to(ship.global_position) <= boarding_range:
		hint_label.text = "%s · BOARD SHIP" % use_label
		return
	if eva.global_position.distance_to(sample.global_position) <= 2.2 and not sample_collected:
		hint_label.text = "%s · COLLECT SAMPLE" % use_label if sample.scanned else "SCAN BEFORE COLLECTION"
		return
	if eva.global_position.distance_to(ruin.global_position) <= 3.0 and not tutorial.completed.has("archaeology"):
		hint_label.text = "%s · INSPECT FOUNDATION" % use_label
		return
	var site := campaign_world.nearest_site(eva.global_position)
	if site != null:
		if site.scanned: hint_label.text = "%s · %s" % [use_label, site.display_name.to_upper()]
		else: hint_label.text = "SCAN · %s" % site.display_name.to_upper()

func _update_campaign_ui() -> void:
	if campaign_label == null or ship_status_label == null: return
	var location := current_world if not current_world.is_empty() else "DEEP SPACE"
	var slice_fragments: int = mini(campaign.fragment_count(), 2)
	campaign_label.text = "TETHYS/KESTRA SLICE · %s\nFIRST-HOUR EVIDENCE %d / 2 · ROUTE %s" % [location.to_upper(), slice_fragments, campaign.selected_world.to_upper()]
	ship_status_label.text = "FUEL %.0f / %.0f · HULL %.0f / %.0f" % [ship.fuel, ship.max_fuel, ship.hull, ship.max_hull]

func _save_game() -> void:
	var tutorial_state := tutorial.snapshot() if tutorial != null else {}
	SaveSystem.save_state({"campaign": campaign.snapshot(), "tutorial": tutorial_state})

func _set_mode(value: String) -> void:
	mode = value
	var ship_active := value == "ship"
	eva.set_active(not ship_active)
	ship.set_active(ship_active)
	if mobile_controls: mobile_controls.set_mode(value)
	if ship_active:
		eva.global_position = ship.global_position + Vector3(0, 0.4, 0)
	else:
		var exit_offset := ship.global_transform.basis.z.normalized() * 4.8
		eva.global_position = ship.global_position + exit_offset + Vector3(0, 0.1, 0)
		eva.rotation.y = ship.rotation.y

func _set_eva_cinematic_visible(value: bool) -> void:
	if world_art.has("eva_visual"):
		WorldArt.set_eva_cinematic_visible(world_art["eva_visual"] as Node3D, value)

func _play_intro_cutscene() -> void:
	cutscene_active = true
	eva.enabled = false
	ship.enabled = false
	_set_eva_cinematic_visible(true)
	if mobile_controls: mobile_controls.visible = false
	intro_camera.current = true
	eva.camera.current = false
	ship.camera.current = false
	intro_camera.global_position = Vector3(14, 10, 18)
	intro_camera.look_at(Vector3(0, 1, -5), Vector3.UP)
	_intro_tween = create_tween()
	_intro_tween.tween_property(intro_camera, "global_position", Vector3(-10, 6, 10), 3.2).set_trans(Tween.TRANS_SINE).set_ease(Tween.EASE_IN_OUT)
	_intro_tween.tween_callback(_finish_cutscene)

func _play_reveal_cutscene() -> void:
	cutscene_active = true
	eva.enabled = false
	ship.enabled = false
	_set_eva_cinematic_visible(true)
	if mobile_controls: mobile_controls.visible = false
	intro_camera.current = true
	eva.camera.current = false
	intro_camera.global_position = ruin.global_position + Vector3(6, 4, 7)
	intro_camera.look_at(ruin.global_position, Vector3.UP)
	_intro_tween = create_tween()
	_intro_tween.tween_property(intro_camera, "global_position", ruin.global_position + Vector3(-5, 3, 5), 1.8)
	_intro_tween.tween_callback(_finish_cutscene)

func _finish_cutscene() -> void:
	if _intro_tween and _intro_tween.is_running(): _intro_tween.kill()
	cutscene_active = false
	intro_camera.current = false
	_set_eva_cinematic_visible(false)
	_set_mode(mode)
	if mobile_controls: mobile_controls.visible = DisplayServer.is_touchscreen_available()